let express = require("express")
let {login, createAdmin} = require("../Controllers/usercont")
const { createDoctor, getAllDoctors, getDoctorByEmail, deleteDoctor, updateDoctor } = require("../Controllers/doctorcont")
const {bookAppointment, getAllAppointments, updateAppointmentStatus, cancelAppointment, completeAppointment, deleteAppointment, getAppointmentsByDoctorId, getAppointmentsByPatientId, getAppointmentsByDate, getAppointmentByStatus, getDoctorAppointments, getPatientAppointments, getDoctorPatients, } = require("../Controllers/appointmentcont")
const { createPatient, getAllPatients, getPatientByEmail, updatePatient, deletePatient } = require("../Controllers/patientcont")
let rt = new express.Router()
rt.post("/login",login)
rt.post("/createadmin",createAdmin)
rt.post("/createdoctor",createDoctor)
rt.get("/getalldoctors",getAllDoctors)
rt.get("/getdoctorbyemail/:email",getDoctorByEmail)
rt.put("/updatedoctor/:email",updateDoctor)
rt.delete("/deletedoctor/:email",deleteDoctor)

rt.post("/createpatient",createPatient)
rt.get("/getallpatients",getAllPatients)
rt.get("/getpatientbyemail/:email",getPatientByEmail)
rt.put("/updatepatient/:email",updatePatient)
rt.delete("/deletepatient/:email",deletePatient)

rt.post('/bookappointment',bookAppointment)
rt.get('/getallappointments',getAllAppointments)
rt.get('/getappointmentbystatus/:status',getAppointmentByStatus)
rt.put('/updateappointmentstatus/:id',updateAppointmentStatus)          
rt.put('/cancelappointment/:id',cancelAppointment)
rt.put('/completeappointment/:id',completeAppointment)
rt.delete('/deleteappointment/:id',deleteAppointment)
rt.get("/getdoctorpatients/:email",getDoctorPatients)
rt.get('/getappointmentsbydate/:date',getAppointmentsByDate)
rt.get("/getdoctorappointments/:email",getDoctorAppointments)
rt.get("/getpatientappointments/:email",getPatientAppointments)

module.exports = rt